name: CI
on:
  pull_request:
  push:

jobs:
  spec:
    name: "RSpec / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "head"]
    steps:
      - run: sudo apt-get install libcurl4-openssl-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
